[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "plone.classicui"
version = "1.0.0a1.dev0"
description = "Plone Classic UI distribution."
readme = "README.md"
license = "gpl-2.0-only"
requires-python = ">=3.10"
authors = [
    { name = "Plone Foundation", email = "releasemanager@plone.org" },
]
keywords = [
    "CMS",
    "Distribution",
    "Plone",
    "Python",
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Environment :: Web Environment",
    "Framework :: Plone",
    "Framework :: Plone :: 6.1",
    "Framework :: Plone :: Addon",
    "Framework :: Plone :: Distribution",
    "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "Products.CMFPlone",
    "plone.distribution",
]

[project.optional-dependencies]
test = [
    "plone.app.testing",
]

[project.urls]
Homepage = "https://github.com/plone/plone.classicui"
Source = "https://github.com/plone/plone.classicui"
Tracker = "https://github.com/plone/plone.classicui/issues"

[tool.hatch.build.targets.sdist]
include = [
    "/src",
]

# Generated from:
# https://github.com/plone/meta/tree/master/config/default
[tool.towncrier]
filename = "CHANGES.rst"
directory = "news/"
title_format = "{version} ({project_date})"
underlines = ["-", ""]

[[tool.towncrier.type]]
directory = "breaking"
name = "Breaking changes:"
showcontent = true

[[tool.towncrier.type]]
directory = "feature"
name = "New features:"
showcontent = true

[[tool.towncrier.type]]
directory = "bugfix"
name = "Bug fixes:"
showcontent = true

[[tool.towncrier.type]]
directory = "internal"
name = "Internal:"
showcontent = true

[[tool.towncrier.type]]
directory = "documentation"
name = "Documentation:"
showcontent = true

[[tool.towncrier.type]]
directory = "tests"
name = "Tests"
showcontent = true

[tool.isort]
profile = "plone"

[tool.black]
target-version = ["py38"]
